language: android
jdk:
- oraclejdk8
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-16
  - android-22
  - android-26

  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-16
  - sys-img-armeabi-v7a-android-22

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - if [[ "$TRAVIS_BRANCH" != "master" ]];then ./gradlew clean lint test connectedCheck -PdisablePreDex --continue --stacktrace; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]];then ./gradlew clean lint test assembleRelease; fi

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

before_install:
- echo $secret_password | gpg --passphrase-fd 0 configuration-release.tar.gpg
- tar xvf configuration-release.tar
- chmod +x gradlew

deploy:
  provider: releases
  api_key:
    secure: O7okXVtzoIdKRPKCFEeVftRZm7qYTzo0TxTIirExbcqmfCAtvirpqcdaF54+gwpKW5rRLwbXfYGiDSqsJ7QN+5X/iDB5gC/WwqcLVgLjR5OOfxjnBmzy2PYQC9phu1a4KRrThHKATy4hJInsMflCEZqcxknTyjP7KQl1H7YOC0eJioImS2qY10JbSEtSFk+pSkgUijCHlBjHO1XZZr4HD9VVw8wk897Ncx/h987q/NBICOgw5GuRau8kXvS3rbzao+OBTAQAHMLREoeRQ+2qXTLb19w3KTfDhoR3HAuUpLa/lGbUX80WGFrW8XvC7gJeTFhul1GNLdMbLKwZ0cH8tJl2YIHPxUOmdvolMGyNQM5T++4is6LTE3gmIGSwpRGfe1PjP9qV+WMhmYLs40Kr7tTYRK1RbYHQFKoRu32Uxzzx2CHOz/LStSzaSzcKFpIIJwWrjQYDTBpfAvk+EKw9qHMmDJVNrDbmyZudSlMFqLrDoyrHSKrsbhp1oX4V5BhqmesM5t8K8mM2H1UyW4o8O6Un87keouYouVjVIEGdermw/DzstHflVRlqeqvc5Hrmw2DYWwqtbZVCqzu4XnvjOEAm9ClrXN1lqbVFrBeWcV9VEsyneolNokV2U7LEJ7BXKnhNx9K+n2U1qATvmDG6AwWlDSypSi22x9L85jxuxok=
  file_glob: true
  file: app/build/output/*-release.apk
  skip_cleanup: true
  on:
    repo: ngengs/android_Baking-Apps
    branch: master

env:
  global:
    - ADB_INSTALL_TIMEOUT=15
    - secure: rNr255SGGFLZY2riTW4XA0Vu8fHIiRrF688NwEXGQVfOGfUQxa3gcnLKc0w4QJ12eaG/ywRwuCOf9E1qQtxjM2Yq4NdeMQxKNhkZRBUG4wz63Qmx1D2eYnKPtEQG8EIu4NlFCTnBiwxHRQ1F6CynFT+2lyoaMnbT13i866p4EMFEpnJ94Wm0WGzKRuxJ53rimPVNNxX4d6Hvx1xsIiQqADhVZzNZ9PKfO44woilJB/SPF/HD2MJM1nU9L4oUrnrBHHdBJ1hNU+pBxfCDOLWVDPskBKGoSY/V9mJImaKB60DcVQLfl3Qvh4aVM/BqedZ28j/c3B2pSuFwd1wIx1mxhK2OFbfuxgg+PizXjMZQM+Z/fj+NsCz5KEJj8LficGP2b1sHodTUmmOkgrFIzTwNtCFn2EbtLHqLfxKFNdhvIv1uKVIPlJAzVDpS8W5E8H4SvtBBGzjcXyMJe6yaw1HkXW6GPexTUXjjNWvpOvfuy9tXmi7T5WgYVtcOkZinBsnQY355ay3Au5ZS5xj2cKjY/pom34YmnD1PvXWb9nVe7v8pyiJY2OMJGqgt3ycPDclR7H7hH7+OiiqpecJW1CKpjov9gZGNkdEmrHDGUDTOQy6FRYYURgQcb08Mr1jTWxdUYXfwRpbv5oNP5KSH3I05PCMTDmz+rdZSA/uGEDyMkMQ=
  matrix:
    - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

after_failure:
  - wget https://raw.githubusercontent.com/tremby/imgur.sh/master/imgur.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' > screen.png
  - ./imgurbash.sh screen.png
  - cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml