language: android
jdk:
- oraclejdk8
android:
  components:
  - extra-google-m2repository
  - extra-android-m2repository
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]];then ./gradlew clean assembleRelease; else ./gradlew clean lint test assembleRelease;fi
before_install:
- openssl aes-256-cbc -k "password_configuration" -in configuration-release.tar.enc -out configuration-release.tar -d
- tar xvf configuration-release.tar
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: O7okXVtzoIdKRPKCFEeVftRZm7qYTzo0TxTIirExbcqmfCAtvirpqcdaF54+gwpKW5rRLwbXfYGiDSqsJ7QN+5X/iDB5gC/WwqcLVgLjR5OOfxjnBmzy2PYQC9phu1a4KRrThHKATy4hJInsMflCEZqcxknTyjP7KQl1H7YOC0eJioImS2qY10JbSEtSFk+pSkgUijCHlBjHO1XZZr4HD9VVw8wk897Ncx/h987q/NBICOgw5GuRau8kXvS3rbzao+OBTAQAHMLREoeRQ+2qXTLb19w3KTfDhoR3HAuUpLa/lGbUX80WGFrW8XvC7gJeTFhul1GNLdMbLKwZ0cH8tJl2YIHPxUOmdvolMGyNQM5T++4is6LTE3gmIGSwpRGfe1PjP9qV+WMhmYLs40Kr7tTYRK1RbYHQFKoRu32Uxzzx2CHOz/LStSzaSzcKFpIIJwWrjQYDTBpfAvk+EKw9qHMmDJVNrDbmyZudSlMFqLrDoyrHSKrsbhp1oX4V5BhqmesM5t8K8mM2H1UyW4o8O6Un87keouYouVjVIEGdermw/DzstHflVRlqeqvc5Hrmw2DYWwqtbZVCqzu4XnvjOEAm9ClrXN1lqbVFrBeWcV9VEsyneolNokV2U7LEJ7BXKnhNx9K+n2U1qATvmDG6AwWlDSypSi22x9L85jxuxok=
  file_glob: true
  file: app/build/output/*-release.apk
  skip_cleanup: true
  on:
    repo: ngengs/android_Baking-Apps
    branch: master
env:
  global:
    secure: Oj+HQbGAd+zb24OgUFDOGlNgT1YvpCXUV/+LGc2CG27EqnLHZ7xejEY0t3+DzP6m9QM6Vyuo2WXOgYlvVuO6ocjJJ6uARYUkJpPWyNlhX+ZIHSvvUu0eFn0WPWT8UGHHhzk6xmuIa+vIW8qYi6C3+nldN6lcsVOpKvgVNoih2YsAjNtTN/4+X1ARZ85ARCiWW3rKJJVcCASeG33QHkE4E39ea54Qz80LzcrIjx8EC1mNaIjb7RpP6f8a0WVtCDd4L+nea/7XP+AxDA/2RutykAejKoyKp6o8hNr0iK6rQHzNvTXzAL7ZQvPVT/hKjanCKYckxkVs1Nthl61zAjR8TVRCH1ddSYAy341B4RmEpDF4milCs+vc9TjBy+PjVU3niVz7v1t1U8VAksGclDmXYFbHDcmMkiM1QheNnuY+6SShCY6YylsJIcF/3o+A7/yEoC3I7e4SIV0ESIwZ4XVvkLMEyr9ouf0nPEFkNJ5Y+xAa/Vk0RvL9xlSO+bhLF0myV5mUmu7khri74ol7xq9nSQ5R0uY+3hhhn8ue6d56i2jWyzomJvC8VpLwUPfiwrT5UUovCHhszKjWccyvVoHh9gPPl6N+2TC93UtHaXw9c6TO380U+R/fePL/Fl9wyK7m+nd3uUeYPpMiW6TDXBpszOZcATdGsrUFLE2XhbRVYpw=
